@echo off
echo Building Mena Business Desktop App...
echo 1. Cleaning old builds...
if exist dist rd /s /q dist
if exist build rd /s /q build
echo 2. Installing dependencies (if needed)...
call npm install
echo 3. Building Frontend and Backend...
call npm run build
echo 4. Packaging Desktop App...
call npm run dist
echo.
echo Build complete! Your installer is in the 'build' folder.
pause
